[package]
name = "yasg"
version = "0.1.0"
authors = ["Claes Gyllensv√§rd <letharion@gmail.com>"]

[dependencies]
futures = "0.1.18"
tokio = "0.0.0"
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.43.0"

gfx_text = "0.17.0"
